name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        echo "No tests defined yet."

    - name: Build Docker image
      run: |
        docker build -t kavanportfolio .

- name: Deploy to AWS EC2
  run: |
    chmod 400 kavan.pem
    ssh -o StrictHostKeyChecking=no -i kavan.pem ubuntu@3.92.186.218 << 'EOF'
      cd ~/kavanprotfolio || { git clone https://github.com/krunalpatel355/kavanprotfolio.git kavanprotfolio && cd kavanprotfolio; }
      git pull origin master
      docker stop kavanportfolio-container || true
      docker rm kavanportfolio-container || true
      docker build -t kavanportfolio .
      docker run -d -p 80:5000 --name kavanportfolio-container kavanportfolio
    EOF